name: Hello World
on: 
  push:
    branches:
      - main

jobs:
  Greetings:
    runs-on: ubuntu-latest
      steps:
        - name:message
          run: echo "Hello World.!!!"
        - name: nodeversion
          run: |
            node -v
            npm -v
